### PR TITLE
Added ability to configure module to be hidden if there is no new mail

### PR DESCRIPTION
**Pull request by jamescross4**
This adds the configuration to automatically hide the GmailFeed module if there are no new emails in the user's inbox. If a new email arrives, the module appears and when the email is opened, the module disappears.

### CODE REVIEW

**Comment by jamescross449** [comment]
Also added notification mode option

**Comment by Adarsh-Suvarna** [comment]
I tried this module.
Module is loaded correctly. Whenever new mail comes it plays notification sound.
But I'm not getting any information about mail in magic mirror window.
It's just a blank and not showing any emails or headers.

**Comment by smirror293** [comment]
Hey, I have a question. I am Using raspberry pi 4 and email is not showing on my screen. I have done all the procedures as per the guide. Can i know what should be the problem?

**Comment by shaneapowell** [comment]
Hey james.. sorry I dind't get to this PR ... I just didn't notice it.   I like what you've done with the little tweaks.. let me take a closer look and try and pull your changes into my repo.

**Comment by zynapsid** [comment]
Hi Shane, the latest commit breaks the module MMM-Pages so all modules are seen on the first page (the module MMM-Todoist also did this), if there's anything that could be done to address the issue that would be great.  It also appears to effect the popular GA module https://forum.magicmirror.builders/topic/16364/mmm-gmailfeed?_=1645088334327

**Comment by KristjanESPERANTO** [comment]
Unfortunately it's not possible to create issues here at this project. @shaneapowell do you like to change that?

@zynapsid Can you provide a config with which we can easily reproduce this?

**Comment by shaneapowell** [comment]
@KristjanESPERANTO Issues enabled.

**Comment by KristjanESPERANTO** [comment]
PR #3 should fix the issue :slightly_smiling_face: 

Commit https://github.com/shaneapowell/MMM-GmailFeed/pull/3/commits/e6f6fab993d0664183a7aaac9ecf45be7f4cc4c3 is the the significant one.

**Pull request merged**
